name: Generate Javadoc

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages-${{ github.workflow }}"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Setup Java
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Setup Gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      # Make Gradle wrapper executable
      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      # Install Toolchain
      - name: Install toolchain
        run: ./gradlew installRoboRioToolchain

      # Generate Javadoc
      - name: Generate Javadoc
        run: ./gradlew javadoc

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      # Clean HTML files
      - name: Clean HTML files
        env:
          REPLACEMENTS: ${{ env.REPLACEMENTS }}
        run: |
          for file in $(find build/docs/javadoc -name "*.html"); do
            sed -i "$REPLACEMENTS" "$file"
            echo "Processed $file"
          done

      - name: Install minify
        run: bun install -g minify

      # Minify HTML files
      - name: Minify HTML files
        run: |
          for file in $(find build/docs/javadoc -name "*.html"); do
            minify "$file" > "${file}.min"
            mv "${file}.min" "$file"
            echo "Minified HTML: $file"
          done

      # # Minify JavaScript files
      # - name: Minify JavaScript files
      #   run: |
      #     for file in $(find build/docs/javadoc -name "*.js"); do
      #       minify "$file" > "${file}.min"
      #       mv "${file}.min" "$file"
      #       echo "Minified JavaScript: $file"
      #     done

      # Minify CSS files
      - name: Minify CSS files
        run: |
          for file in $(find build/docs/javadoc -name "*.css"); do
            minify "$file" > "${file}.min"
            mv "${file}.min" "$file"
            echo "Minified CSS: $file"
          done

      # Upload the Javadoc as a Pages artifact
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/docs/javadoc

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
